name: Run Build and Tests

on:
  push:
    paths:
      - "examtopics-downloader/**.go"
      - "examtopics-downloader/go.mod"
      - ".github/workflows/go-tests.yml"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build project
        run: cd examtopics-downloader && go build ./...

      - name: Run tests
        run: cd examtopics-downloader && go test -v ./tests
